services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: TodoApplicationDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:test1234@db:5432/TodoApplicationDatabase
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./TodoApp:/app/TodoApp  # for hot reload during dev
    command: uvicorn TodoApp.main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  postgres_data: